version: 0.2
phases:
  install:
    commands:
      - pip install -r requirements.txt -t src/
  build:
    commands:
      - cd src
      - zip -r ../lambda.zip .
artifacts:
  files:
    - lambda.zip
